const mapPlaces = [
  { id: "guide-okhotny", type: "metro", name: "Охотный Ряд", nameEn: "Okhotny Ryad", lat: 55.7577, lon: 37.6156, description: "Удобная точка старта для прогулки по Красной площади, Кремлю и Театральной площади.", descriptionEn: "A convenient starting point for Red Square, the Kremlin and Theatre Square.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Okhotny_Ryad_station_Moscow.jpg/640px-Okhotny_Ryad_station_Moscow.jpg" },
  { id: "guide-kropotkinskaya", type: "metro", name: "Кропоткинская", nameEn: "Kropotkinskaya", lat: 55.7453, lon: 37.6037, description: "Отсюда легко выйти к Храму Христа Спасителя, Пречистенке и набережным Москвы-реки.", descriptionEn: "A good gateway to the Cathedral of Christ the Saviour, Prechistenka and the river embankments.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Kropotkinskaya_station_01.jpg/640px-Kropotkinskaya_station_01.jpg" },
  { id: "guide-park-kultury", type: "metro", name: "Парк культуры", nameEn: "Park Kultury", lat: 55.7357, lon: 37.5947, description: "Удобный вход к Парку Горького, Музеону и прогулкам вдоль Москвы-реки.", descriptionEn: "A convenient entrance to Gorky Park, Muzeon and walks along the Moskva River.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Park_Kultury_station_Moscow.jpg/640px-Park_Kultury_station_Moscow.jpg" },
  { id: "guide-gorky", type: "park", name: "Парк Горького", nameEn: "Gorky Park", lat: 55.7298, lon: 37.6011, description: "Большой городской парк с широкими аллеями, набережной и местами для спокойной остановки.", descriptionEn: "A large city park with broad paths, a riverside promenade and plenty of places to pause.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Gorky_Park_%282013-07-16%29_01.jpg/640px-Gorky_Park_%282013-07-16%29_01.jpg" },
  { id: "guide-zaryadye", type: "park", name: "Парк Зарядье", nameEn: "Zaryadye Park", lat: 55.7517, lon: 37.6286, description: "Небольшой парк у Кремля с необычным ландшафтом, видами на реку и парящим мостом.", descriptionEn: "A compact park by the Kremlin with unusual landscapes, river views and a floating bridge.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Zaryadye_Park_in_Moscow.jpg/640px-Zaryadye_Park_in_Moscow.jpg" },
  { id: "guide-sokolniki", type: "park", name: "Сокольники", nameEn: "Sokolniki Park", lat: 55.7958, lon: 37.6758, description: "Просторный лесопарк с аллеями, прудами и более спокойным ритмом прогулки.", descriptionEn: "A spacious forest park with paths, ponds and a slower walking rhythm.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Sokolniki_Park%2C_Moskva%2C_Russia_%28Unsplash%29.jpg/640px-Sokolniki_Park%2C_Moskva%2C_Russia_%28Unsplash%29.jpg" },
  { id: "guide-red-square", type: "sight", name: "Красная площадь", nameEn: "Red Square", lat: 55.7539, lon: 37.6208, description: "Главная площадь Москвы и естественный центр прогулки по историческому центру города.", descriptionEn: "Moscow's main square and a natural centre for exploring the historic city core.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Red_Square%2C_Moscow%2C_Russia.jpg/640px-Red_Square%2C_Moscow%2C_Russia.jpg", article: "red-square" },
  { id: "guide-st-basil", type: "sight", name: "Собор Василия Блаженного", nameEn: "Saint Basil's Cathedral", lat: 55.7525, lon: 37.6231, description: "Самый узнаваемый силуэт Красной площади, который хорошо рассматривать с разных подходов.", descriptionEn: "The most recognisable silhouette on Red Square, best viewed from several approaches.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Church_of_the_Savior_on_Blood-2016.jpg/640px-Church_of_the_Savior_on_Blood-2016.jpg", article: "st-basil" },
  { id: "guide-tretyakov", type: "sight", name: "Третьяковская галерея", nameEn: "Tretyakov Gallery", lat: 55.7414, lon: 37.6208, description: "Один из главных художественных музеев страны в тихом и атмосферном Замоскворечье.", descriptionEn: "One of Russia's leading art museums, set in the atmospheric Zamoskvorechye district.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/State_Tretyakov_Gallery_Moscow.jpg/640px-State_Tretyakov_Gallery_Moscow.jpg", article: "tretyakov" },
  { id: "guide-arbat", type: "sight", name: "Старый Арбат", nameEn: "Old Arbat", lat: 55.7498, lon: 37.5912, description: "Пешеходная улица с историческими фасадами, уличными деталями и удобным темпом прогулки.", descriptionEn: "A pedestrian street with historic facades, street details and an easy walking pace.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/ArbatMoscow.jpg/640px-ArbatMoscow.jpg", article: "arbat" },
  { id: "guide-vdnh", type: "sight", name: "ВДНХ", nameEn: "VDNKh", lat: 55.8278, lon: 37.6263, description: "Монументальный ансамбль, павильоны и большие прогулочные пространства на севере Москвы.", descriptionEn: "A monumental ensemble of pavilions and generous walking spaces in northern Moscow.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Moscow_VDNKh_Armenia_Pavilion_asv2018-08_img1.jpg/640px-Moscow_VDNKh_Armenia_Pavilion_asv2018-08_img1.jpg", article: "vdnh" },
];
