const curatedRoutes = [
  { slug: "red-square-classic", title: "Красная площадь и Зарядье", enTitle: "Red Square and Zaryadye", description: "Короткая прогулка через главные символы исторического центра и виды на Москву-реку.", enDescription: "A compact walk through Moscow’s historic icons and river views.", start: "metro-okhotny", distance: 4, theme: "classic", anchor: "zaryadye", tags: ["центр", "история"], stops: ["Красная площадь", "Александровский сад", "Никольская улица", "Парк Зарядье"] },
  { slug: "gorky-waterfront", title: "Парк Горького и набережная", enTitle: "Gorky Park and the Waterfront", description: "Спокойный маршрут у воды с парком, мостами и зелёными аллеями.", enDescription: "A relaxed waterfront walk through parks, bridges and green paths.", start: "metro-park-kultury", distance: 6, theme: "water", anchor: "gorky", tags: ["вода", "парки"], stops: ["Крымский мост", "Музеон", "Парк Горького", "Нескучный сад"] },
  { slug: "patriki-architecture", title: "Патрики и Тверские бульвары", enTitle: "Patriki and Tverskoy Boulevards", description: "Вечерняя прогулка по тихим улицам, прудам и историческим фасадам.", enDescription: "An evening walk through quiet streets, ponds and historic façades.", start: "metro-mayakovskaya", distance: 4, theme: "architecture", anchor: "patriarshiye", tags: ["архитектура", "вечер"], stops: ["Патриаршие пруды", "Спиридоновка", "Малая Бронная", "Тверской бульвар"] },
  { slug: "vdnh-green", title: "ВДНХ и Останкинский парк", enTitle: "VDNH and Ostankino Park", description: "Большая зелёная прогулка с павильонами, фонтанами и парком.", enDescription: "A broad green walk with pavilions, fountains and park paths.", start: "metro-vdnkh", distance: 8, theme: "green", anchor: "vdnh", tags: ["парки", "архитектура"], stops: ["ВДНХ", "Фонтан Дружба народов", "Павильон Космос", "Останкинский парк"] },
  { slug: "arbat-prechistenka", title: "Арбат и Пречистенка", enTitle: "Arbat and Prechistenka", description: "Исторические улицы, переулки и архитектура вокруг Храма Христа Спасителя.", enDescription: "Historic streets, lanes and architecture around the Cathedral of Christ the Saviour.", start: "metro-kropotkinskaya", distance: 4, theme: "architecture", anchor: "arbat", tags: ["центр", "архитектура"], stops: ["Храм Христа Спасителя", "Пречистенка", "Остоженка", "Старый Арбат"] },
  { slug: "kolomenskoye-park", title: "Коломенское и виды на реку", enTitle: "Kolomenskoye and River Views", description: "Длинная прогулка по усадьбе, садам и открытым видам на Москву-реку.", enDescription: "A long walk through an estate, gardens and open river views.", start: "metro-tretyakovskaya", distance: 12, theme: "green", anchor: "kolomenskoye", tags: ["усадьбы", "природа"], stops: ["Коломенское"] },
  { slug: "zamoskvorechye-art", title: "Третьяковка и Замоскворечье", enTitle: "Tretyakov Gallery and Zamoskvorechye", description: "Музей, тихие переулки и набережные южнее Кремля.", enDescription: "Art, quiet lanes and waterfronts south of the Kremlin.", start: "metro-tretyakovskaya", distance: 4, theme: "architecture", anchor: "tretyakov", tags: ["искусство", "центр"], stops: ["Третьяковская галерея", "Лаврушинский переулок", "Кадашёвская набережная", "Пятницкая улица"] },
  { slug: "novodevichy-river", title: "Новодевичий монастырь и пруды", enTitle: "Novodevichy Convent and Ponds", description: "Тихий исторический ансамбль и вода рядом с Лужниками.", enDescription: "A peaceful historic ensemble and ponds near Luzhniki.", start: "metro-park-kultury", distance: 6, theme: "water", anchor: "novodevichy", tags: ["история", "вода"], stops: ["Новодевичий монастырь", "Новодевичьи пруды", "Лужники"] },
  { slug: "sokolniki-green", title: "Сокольники и Аптекарский огород", enTitle: "Sokolniki and Aptekarsky Ogorod", description: "Зелёный маршрут от центра к большим парковым аллеям.", enDescription: "A green route from the centre to broad park avenues.", start: "metro-chistye", distance: 8, theme: "green", anchor: "sokolniki", tags: ["парки", "зелень"], stops: ["Чистые пруды", "Аптекарский огород", "Сокольники"] },
  { slug: "moscow-city-river", title: "Москва-Сити и западная набережная", enTitle: "Moscow City and the Western Waterfront", description: "Современная архитектура и длинная прогулка вдоль реки.", enDescription: "Contemporary architecture and a long riverside walk.", start: "metro-kievskaya", distance: 8, theme: "water", anchor: "moscow-city", tags: ["современная Москва", "вода"], stops: ["Москва-Сити", "Набережная Тараса Шевченко", "Лужники"] },
  { slug: "tsaritsyno-estate", title: "Царицыно: дворцы и пруды", enTitle: "Tsaritsyno: Palaces and Ponds", description: "Большой парк с дворцовым ансамблем и прогулкой у воды.", enDescription: "A large park with palace architecture and ponds.", start: "metro-tretyakovskaya", distance: 12, theme: "architecture", anchor: "tsaritsyno", tags: ["усадьбы", "архитектура"], stops: ["Царицыно"] },
  { slug: "bolshoi-boulevards", title: "Большой театр и бульвары", enTitle: "Bolshoi Theatre and Boulevards", description: "Парадный центр, театральная площадь и зелёные бульвары.", enDescription: "The grand centre, Theatre Square and leafy boulevards.", start: "metro-okhotny", distance: 4, theme: "classic", anchor: "bolshoi", tags: ["центр", "архитектура"], stops: ["Манежная площадь", "Большой театр", "Петровский бульвар", "Страстной бульвар"] },
  { slug: "sparrow-hills-view", title: "Воробьёвы горы и Лужники", enTitle: "Sparrow Hills and Luzhniki", description: "Видовая прогулка с лесными дорожками и открытой панорамой Москвы.", enDescription: "A scenic walk with woodland paths and a broad Moscow panorama.", start: "metro-park-kultury", distance: 8, theme: "water", anchor: "sparrow", tags: ["виды", "природа"], stops: ["Крымский мост", "Нескучный сад", "Воробьёвы горы", "Лужники"] },
  { slug: "pokrovka-chistye", title: "Покровка и Чистые пруды", enTitle: "Pokrovka and Chistye Prudy", description: "Городская прогулка по живым улицам, бульварам и воде.", enDescription: "A lively city walk through streets, boulevards and water.", start: "metro-chistye", distance: 4, theme: "classic", anchor: "chistye-prudy", tags: ["улицы", "вечер"], stops: ["Мясницкая улица", "Чистые пруды", "Покровка", "Сретенский бульвар"] },
];

const routeBySlug = Object.fromEntries(curatedRoutes.map((route) => [route.slug, route]));

const routeImages = {
  "red-square-classic": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Red_Square%2C_Moscow%2C_Russia.jpg/1280px-Red_Square%2C_Moscow%2C_Russia.jpg",
  "gorky-waterfront": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Gorky_Park_%282013-07-16%29_01.jpg/1280px-Gorky_Park_%282013-07-16%29_01.jpg",
  "patriki-architecture": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Patriarch_Ponds.jpg/1280px-Patriarch_Ponds.jpg",
  "vdnh-green": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Moscow_VDNKh_Armenia_Pavilion_asv2018-08_img1.jpg/1280px-Moscow_VDNKh_Armenia_Pavilion_asv2018-08_img1.jpg",
  "arbat-prechistenka": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/ArbatMoscow.jpg/1280px-ArbatMoscow.jpg",
  "kolomenskoye-park": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Kolomenskoye%2C_Moscow%2C_Russia_-_30062345825.jpg/1280px-Kolomenskoye%2C_Moscow%2C_Russia_-_30062345825.jpg",
  "zamoskvorechye-art": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/State_Tretyakov_Gallery_Moscow.jpg/1280px-State_Tretyakov_Gallery_Moscow.jpg",
  "novodevichy-river": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/2024_Novodevichy_Convent_in_Moscow.jpg/1280px-2024_Novodevichy_Convent_in_Moscow.jpg",
  "sokolniki-green": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Sokolniki_Park%2C_Moskva%2C_Russia_%28Unsplash%29.jpg/1280px-Sokolniki_Park%2C_Moskva%2C_Russia_%28Unsplash%29.jpg",
  "moscow-city-river": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Moscow_International_Business_Centre%2C_Marc_2008.JPG/1280px-Moscow_International_Business_Centre%2C_Marc_2008.JPG",
  "tsaritsyno-estate": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Moscow%2C_Russia%2C_Tsaritsyno_Palace.jpg/1280px-Moscow%2C_Russia%2C_Tsaritsyno_Palace.jpg",
  "bolshoi-boulevards": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Teatro_Bolsh%C3%B3i%2C_Mosc%C3%BA%2C_Rusia%2C_2016-10-03%2C_DD_42-43_HDR.jpg/1280px-Teatro_Bolsh%C3%B3i%2C_Mosc%C3%BA%2C_Rusia%2C_2016-10-03%2C_DD_42-43_HDR.jpg",
  "sparrow-hills-view": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Sparrow_Hills.jpg/1280px-Sparrow_Hills.jpg",
  "pokrovka-chistye": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Patriarch_Ponds.jpg/1280px-Patriarch_Ponds.jpg",
};
